apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: mariadb
        image: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password

        volumeMounts:
        - mountPath: /usr/share/zoneinfo
          name: timezones       
          readOnly: true
        - mountPath: /var/lib/mariadb
          subPath: mysql
          name: data
          readOnly: false

        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          timeoutSeconds: 5

#        readinessProbe:
#          exec:
            # Check we can execute queries over TCP (skip-networking is off).
 #           command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
 #         initialDelaySeconds: 5
  #        timeoutSeconds: 1

      imagePullSecrets:
      - name: dockerhub
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo
          name: timezones 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 5Gi

# kubectl port-forward mariadb-0 3307:3306

