apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mariadb
spec:
  type: NodePort
  ports:
  - port: 3306
    name: tcp
    nodePort: 30306
    targetPort: tcp
  selector:
    app: mariadb
