apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /Users/Shared/mariadb
