---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: http-server-2
  labels:
    app: demo
    tier: frontend
    release: canary
spec:
  #activeDeadlineSeconds: 300
  #restartPolicy: Never
  containers:
  - name: http-server
    image: index.docker.io/k8smtn/containers-overview
    env:
    - name: SITE
      value: "2"

    ports:  # primarily informational
    - name: http
      containerPort: 8080

    readinessProbe:
      httpGet:
        path: /index.html
        port: http
    livenessProbe:
      httpGet:
        path: /index.html
        port: http
      timeoutSeconds: 1      
