apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: k8smtn/demo-api
        env:
        - name: RESIZE_ADDR
          value: image-resizer:8000
        - name: IMGUR_ID
          valueFrom:
            secretKeyRef:
              name: api
              key: imgur-id
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: sslroots
      volumes:
      - hostPath:
          path: /etc/ssl/certs
        name: sslroots
